# Generated by Django 5.2.7 on 2025-10-13 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
