# Generated by Django 5.2.7 on 2025-10-13 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='duration',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='game',
            name='players',
            field=models.CharField(max_length=10),
        ),
    ]
