# Generated by Django 5.2.7 on 2025-10-14 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_game_duration_alter_game_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='country',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='publisher',
            name='founded',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
